import { NextRequest, NextResponse } from 'next/server'
import { supabaseServer } from '@/lib/supabase-server'
import { sendInviteEmail } from '@/lib/invitations-service'

export async function POST(request: NextRequest) {
  try {
    const supabase = await supabaseServer()
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { data: profile } = await supabase
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profile?.role !== 'admin' && profile?.role !== 'staff') {
      return NextResponse.json({ error: 'Unauthorized: Only admin or staff can send bulk invites' }, { status: 403 })
    }

    const body = await request.json()
    const { invitationId, eventIds, ignoreRateLimit = false } = body

    if (!invitationId || !eventIds || !Array.isArray(eventIds)) {
      return NextResponse.json({ error: 'Invalid request: invitationId and eventIds are required' }, { status: 400 })
    }

    // Get invitation details
    const { data: invitation, error: invitationError } = await supabase
      .from('invitations')
      .select(`
        *,
        guest:guests(email, first_name, last_name, invite_code),
        invitation_events(
          *,
          event:events(name, starts_at, venue, address)
        )
      `)
      .eq('id', invitationId)
      .single()

    if (invitationError || !invitation) {
      return NextResponse.json({ error: 'Invitation not found' }, { status: 404 })
    }

    // Determine which event to use
    const selectedEvents = invitation.invitation_events?.filter((ie: any) => 
      eventIds.includes(ie.event_id)
    ) || []
    
    if (selectedEvents.length === 0) {
      return NextResponse.json({ error: 'No valid events found for invitation' }, { status: 400 })
    }

    // Skip rate limit check if ignoreRateLimit is true
    if (!ignoreRateLimit) {
      // Check rate limit
      const today = new Date().toISOString().split('T')[0]
      const { data: mailLogs } = await supabase
        .from('mail_logs')
        .select('*')
        .eq('token', invitation.token)
        .gte('sent_at', `${today}T00:00:00.000Z`)

      if (mailLogs && mailLogs.length >= 3) {
        return NextResponse.json({ error: 'Daily email limit exceeded for this invitation' }, { status: 429 })
      }
    }

    // Prepare email data
    const guestName = `${invitation.guest.first_name} ${invitation.guest.last_name}`
    
    // For multiple events, use the first event for the main subject and RSVP URL
    const primaryEvent = selectedEvents[0]
    const eventDate = new Date(primaryEvent.event.starts_at).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      timeZone: 'Africa/Lagos',
    })
    const eventTime = new Date(primaryEvent.event.starts_at).toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
      timeZone: 'Africa/Lagos',
    })
    const formattedEventDate = `${eventDate} · ${eventTime}`

    // Generate RSVP URL
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://brendabagsherdiamond.com'
    const rsvpUrl = `${baseUrl}/rsvp?token=${invitation.token}`

    // Generate QR code URL
    const qrImageUrl = `${baseUrl}/api/qr?token=${invitation.token}`

    // Generate ICS attachment
    const icsContent = generateIcsAttachment({
      eventName: primaryEvent.event.name,
      startsAt: primaryEvent.event.starts_at,
      venue: primaryEvent.event.venue,
      address: primaryEvent.event.address,
      rsvpUrl
    })

    // Call edge function with new payload
    const { data, error } = await supabase.functions.invoke('send-qr-email', {
      body: {
        to: invitation.guest.email,
        subject: `You're Invited, ${invitation.guest.first_name} — ${selectedEvents.length > 1 ? `${selectedEvents.length} Events` : primaryEvent.event.name}`,
        html: '', // Will be generated by edge function
        text: '', // Will be generated by edge function
        meta: {
          invitationId: invitationId,
          eventIds: eventIds,
          rsvpUrl,
          guestName,
          inviteCode: invitation.guest.invite_code,
          events: selectedEvents.map((event: any) => ({
            id: event.event_id,
            name: event.event.name,
            startsAtISO: event.event.starts_at,
            venue: event.event.venue,
            address: event.event.address,
          })),
          primaryEvent: {
            id: primaryEvent.event_id,
            name: primaryEvent.event.name,
            startsAtISO: primaryEvent.event.starts_at,
            venue: primaryEvent.event.venue,
            address: primaryEvent.event.address,
          },
          includeQr: true,
          eventDate: formattedEventDate,
          qrImageUrl,
        },
        attachments: [
          {
            filename: 'event.ics',
            content: icsContent,
            contentType: 'text/calendar',
          },
        ],
      }
    })

    // Log mail attempt
    await supabase
      .from('mail_logs')
      .insert({
        token: invitation.token,
        email: invitation.guest.email,
        sent_at: new Date().toISOString(),
        success: !error,
        error_message: error?.message
      })

    if (error) {
      return NextResponse.json({ error: `Failed to send email: ${error.message}` }, { status: 500 })
    }

    return NextResponse.json({ success: true, message: 'Email sent successfully' })

  } catch (error) {
    console.error('Send bulk invite error:', error)
    return NextResponse.json(
      { error: 'Failed to send bulk invite' },
      { status: 500 }
    )
  }
}

function generateIcsAttachment({
  eventName,
  startsAt,
  venue,
  address,
  rsvpUrl,
}: {
  eventName: string
  startsAt: string
  venue: string
  address?: string
  rsvpUrl: string
}): string {
  const startDate = new Date(startsAt)
  const endDate = new Date(startDate.getTime() + 2 * 60 * 60 * 1000) // 2 hours later
  
  const formatDate = (date: Date) => {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
  }

  const ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Wedding Invitation//EN',
    'BEGIN:VEVENT',
    `UID:${crypto.randomUUID()}@wedding.com`,
    `DTSTART:${formatDate(startDate)}`,
    `DTEND:${formatDate(endDate)}`,
    `SUMMARY:${eventName}`,
    `LOCATION:${venue}${address ? `, ${address}` : ''}`,
    `DESCRIPTION:You're invited to ${eventName}. RSVP at: ${rsvpUrl}`,
    'STATUS:CONFIRMED',
    'SEQUENCE:0',
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n')
  
  return Buffer.from(ics).toString('base64')
}
